# Generated by Django 5.1.6 on 2025-03-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_alter_scrapetask_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapetask',
            name='current_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scrapetask',
            name='last_processed_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapetask',
            name='progress',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='scrapetask',
            name='resume_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapetask',
            name='total_items',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='scrapetask',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('PAUSED', 'Paused'), ('INTERRUPTED', 'Interrupted'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure')], default='PENDING', max_length=12),
        ),
    ]
