# Generated by Django 5.1.6 on 2025-03-09 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_scrapetask_current_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapetask',
            name='selectors',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='scrapetask',
            name='selector',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ScrapeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selector', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stored_results', to='scraper.scrapetask')),
            ],
            options={
                'ordering': ['extracted_at'],
                'indexes': [models.Index(fields=['task', 'extracted_at'], name='scraper_scr_task_id_7f9042_idx')],
            },
        ),
    ]
